### ISSUE TITLE
[BUG] Invalid CSRF Token

### ISSUE THREAD

**Issue by RyushoYosei** [SillyTavern/SillyTavern-Launcher#51]
### Environment

🪟 Windows

### System

Windows

### Describe the problem

After a power outage, I am getting spam of Invalid CSRF Token and Silly Tavern can no longer start. 

Launching...
SillyTavern is listening on: http://127.0.0.1:8000/
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\SillyTavern\Launcher\SillyTavern-Launcher\SillyTavern\server.js:134:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by deffcolony** [comment]
@RyushoYosei try these steps:
1. Open the launcher
2. Go to `Toolbox `->`Troubleshooting`
3. Run the `Remove node_modules folder`
4. Run the `Fix unresolved conflicts or unmerged files [SillyTavern]`
5. Start sillytavern

**Comment by deffcolony** [comment]
@RyushoYosei 
I assume the problem is solved so i am closing the issue now if you still have problem then please reopen it
